apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  annotations:
    recipients.argocd-notifications.argoproj.io: webhook:bitbot, grafana:argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
  signatureKeys:
    - keyID: C91A9911192C187A
    - keyID: 6785F7AF28DE7081
    - keyID: E90A401336C8AAA9
    - keyID: 68907D8BCCD85A5A
    - keyID: B10116B8193F2DBD
    - keyID: 26CDD32189AA2885
