apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: misskey
commonLabels:
  app.kubernetes.io/name: misskey
resources:
  - ./misskey
  - ./redis
  - networkpolicy.yaml
  - ingress.yaml
