[irc.hashbang]
Server = "irc-internal.ircd.svc:6697"
Nick = "HashBot"
UseTLS = true
# because it uses internal traffic
SkipTLSVerify = true
Label = "h"
RemoteNickFormat = "{NICK}/{LABEL}"
NickServNick = "HashBot"
UseSASL = true
UseRelayMsg = true

[irc.libera]
Server = "irc.libera.chat:6697"
Nick = "HashBot"
UseTLS = true
Label = "l"
RemoteNickFormat = "<{NICK}[{LABEL}]> "
NickServNick = "HashBot"
UseSASL = true

[matrix.main]
Server = "https://matrix.org"
Login = "HashBot"
Label = "m"
RemoteNickFormat = "<{NICK}[{LABEL}]> "
# Matterbridge no longer uses usernames, instead uses display names
# To re-enable:
# UseUsername = true
# NoHomeServerSuffix = false
HTMLDisable = true
SpoofUsername = true

[[gateway]]
name = "default"
enable = true

[[gateway.inout]]
account = "irc.hashbang"
channel = "#!"

[[gateway.inout]]
account = "irc.libera"
channel = "#!"

[[gateway.inout]]
account = "matrix.main"
channel = "#!:matrix.org"

[[gateway]]
name = "social"
enable = true

[[gateway.inout]]
account = "irc.hashbang"
channel = "#!social"

[[gateway.inout]]
account = "matrix.main"
channel = "#!social:matrix.org"
