apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  labels:
    app: site
spec:
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: hashbang/site
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
---
apiVersion: v1
kind: Service
metadata:
  name: site
  labels:
    app: site
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: site
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: site-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: hashbang.sh
spec:
  tls:
  - hosts:
    - hashbang.sh
    secretName: site-tls
  rules:
  - host: hashbang.sh
    http:
      paths:
      - path: /
        backend:
          serviceName: site
          servicePort: 80
