apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ircd
resources:
  - certificate.yaml
  - resources.yaml
configMapGenerator:
- name: irc-config
  options:
    disableNameSuffixHash: true
  files:
  - files/ircd.motd
  - files/ircd.yaml
images:
  - name: ghcr.io/ergochat/ergo
    newTag: v2.18.0@sha256:8e2eae935b59f5bd6c0cb567c94d8ab4f825e4c62c532e94ef09a7bbfcef30e6
