apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ircd
resources:
  - certificate.yaml
  - resources.yaml
configMapGenerator:
- name: irc-config
  options:
    disableNameSuffixHash: true
  files:
  - files/ircd.motd
  - files/ircd.yaml
images:
  - name: ghcr.io/ergochat/ergo
    newTag: v2.19.0@sha256:98975f36281cc4d65ed00bfd2764a4e6794ed39c354de385561f74d0c7ad12ef
