apiVersion: apps/v1
kind: Deployment
metadata:
  name: irc-deployment
  labels:
    app: irc
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: irc
  template:
    metadata:
      labels:
        app: irc
    spec:
      shareProcessNamespace: true
      containers:
      - name: irc
        image: oragono/oragono:dev
        ports:
        - containerPort: 6697
          name: ircs
        - containerPort: 443
          name: websocket
        readinessProbe:
          tcpSocket:
            port: 6697
        livenessProbe:
          tcpSocket:
            port: 6697
        volumeMounts:
        - mountPath: /ircd/
          name: irc-config
          readOnly: true
        - mountPath: /ircd/tls
          name: irc-certs
          readOnly: true
        - mountPath: /ircd/db
          name: irc-db
      - name: config-reloader
        # image is based on busybox which includes inotifyd + pkill
        image: oragono/oragono:dev
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            echo "Watching /ircd/";
            inotifyd - /ircd/:wMymndox | while read -r notifies ; do
              echo "$notifies";
              echo "notify received, sending SIGHUP";
              pkill -HUP oragono;
            done
            echo "Exiting.";
        volumeMounts:
        - mountPath: /ircd/
          name: irc-config
          readOnly: true
        - mountPath: /ircd/tls
          name: irc-certs
          readOnly: true
      volumes:
      - name: irc-config
        configMap:
          name: irc-config
      - name: irc-certs
        secret:
          secretName: irc-certs
      - name: irc-db
        persistentVolumeClaim:
          claimName: irc-db
---
apiVersion: v1
kind: Service
metadata:
  name: irc
  labels:
    app: irc
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    external-dns.alpha.kubernetes.io/hostname: "irc.hashbang.sh"
spec:
  type: LoadBalancer
  ports:
  - name: irc
    port: 6697
    targetPort: 6697
  - name: websockets
    port: 443
    targetPort: 443
  selector:
    app: irc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irc-db
  labels:
    app: irc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
