apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/james-callahan/cloudnative-pg-kustomize/configurations?ref=96a350bfc3329bc5bd9b7139527384f965727038 # branch=main
