apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: monitoring
  name: k8s
spec:
  # Hash lock prometheus container
  image: quay.io/prometheus/prometheus@sha256:f4c5fa1018a5c15f81250b8122f36f90146d5c2b323f9ec1f41d1b36dc0e7cb9 # v2.36.1
  # Hash lock helper containers
  containers:
    - name: prometheus-config-reloader
      image: quay.io/prometheus-operator/prometheus-config-reloader@sha256:8c45787645d17c51acb44aa0386af3aa5d8bfd7bddd8d57dd041878b9494c5ff # v0.57.0
    # - name: thanos-sidecar
    #   image:
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  namespace: monitoring
  name: main
spec:
  image: quay.io/prometheus/alertmanager@sha256:088464f949de8065b9da7dfce7302a633d700e9d598e2bebc03310712f083b31 # v0.24.0
  # Hashlocking unsupported for config-reloader
  # https://github.com/coreos/prometheus-operator/issues/3262
  # containers:
