apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: user-auth
    nginx.ingress.kubernetes.io/auth-secret-type: auth-map
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.hashbang.sh
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - grafana.hashbang.sh
    secretName: grafana-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: user-auth
    nginx.ingress.kubernetes.io/auth-secret-type: auth-map
spec:
  ingressClassName: nginx
  rules:
  - host: alertmanager.hashbang.sh
    http:
      paths:
      - backend:
          service:
            name: alertmanager-main
            port:
              number: 9093
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - alertmanager.hashbang.sh
    secretName: alertmanager-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: user-auth
    nginx.ingress.kubernetes.io/auth-secret-type: auth-map
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus.hashbang.sh
    http:
      paths:
      - backend:
          service:
            name: prometheus-k8s
            port:
              number: 9090
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - prometheus.hashbang.sh
    secretName: prometheus-tls
