apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/coreos/kube-prometheus?ref=e3066575dc8be21f578f12887563bda3ee7a2eff # 0.11.0
  - ingress.yaml
  - cilium-service-monitor.yaml
  - ./loki
  - ./promtail
  - prometheus-additional-targets.yaml
  - grafana-role.yaml
patches:
  - container-images.patch.yaml
  - cluster-wide.patch.yaml
  - grafana-auth.patch.yaml
  - grafana-sidecar.patch.yaml
  - prometheus-additional-scrape-configs.patch.yaml
  - prometheus-persistent-volume.patch.yaml
patchesJson6902:
  - target:
      version: v1
      kind: Service
      namespace: monitoring
      name: grafana
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 80
  # Workaround https://github.com/coreos/kube-prometheus/issues/586
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: remove
        path: /status
configMapGenerator:
  - name: grafana-dashboard-cilium
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      # https://github.com/cilium/cilium/tree/6fe8d092a6796d36230a0e3480cd2a8472e1a6f0/examples/kubernetes/addons/prometheus/files/grafana-config
      - files/grafana-dashboard-cilium.json
      - files/grafana-dashboard-cilium-operator.json
  - name: grafana-dashboard-ingress-nginx
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      # https://github.com/kubernetes/ingress-nginx/blob/810acfafbef86d9dc05e0ece68c97d0c93344632/deploy/grafana/dashboards/nginx.json
      - files/grafana-dashboard-ingress-nginx.json
  - name: grafana-dashboard-shell-nodes
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      # modified from https://raw.githubusercontent.com/grafana/kubernetes-app/master/src/dashboards/k8s-node.json
      - files/grafana-dashboard-shell-nodes.json
secretGenerator:
  - name: grafana-datasources
    namespace: monitoring
    behavior: merge
    options:
      disableNameSuffixHash: true
    files:
      - files/datasource-loki.yaml
generators:
  - secret-generator.yaml
images:
  - name: grafana/grafana:8.5.5
    digest: sha256:f247fbae840f874ee3c6c1501f5dde6c768ea07b9893182ebd1f16a10fb725b1
  - name: kiwigrid/k8s-sidecar:0.1.178
    digest: sha256:95feeef7afb892cb781fe67d5d487a087049386888b1f7e84a2c4a63c2f09259
  - name: k8s.gcr.io/prometheus-adapter/prometheus-adapter:v0.9.1
    digest: sha256:d025d1a109234c28b4a97f5d35d759943124be8885a5bce22a91363025304e9d
  - name: quay.io/brancz/kube-rbac-proxy:v0.12.0
    digest: sha256:12b82e47da1a2f5094966d4239811a5ae5c37b47e4224b1b35e57a7f02edd57a
  - name: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.5.0
    digest: sha256:09a36e2be1dbda6009641235d90be8627c9616d42a0b887b770fc92c1753b74a
  - name: quay.io/prometheus-operator/prometheus-operator:v0.57.0
    digest: sha256:a2d502c204f9991d31da4754cb02a2299eb1a4c9e675bb4038c67ebd06b1b94e
  - name: quay.io/prometheus/node-exporter:v1.3.1
    digest: sha256:f2269e73124dd0f60a7d19a2ce1264d33d08a985aed0ee6b0b89d0be470592cd
  - name: quay.io/prometheus/blackbox-exporter:v0.21.0
    digest: sha256:6f260daca488d0b32849a05958c32f9c5db6b960d4553c3b67997387ee81d2f9
  - name: jimmidyson/configmap-reload:v0.5.0
    digest: sha256:91467ba755a0c41199a63fe80a2c321c06edc4d3affb4f0ab6b3d20a49ed88d1
