apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  instances: 2
  smartShutdownTimeout: 3
  storage:
    size: 5Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: cloudnative-pg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudnative-pg:manager-edit
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: cloudnative-pg
