apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/name: keycloak
resources:
  - ../cloudnative-pg/configurations
  - db.yaml
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - ingress.yaml
configMapGenerator:
  - name: keycloak-config
    literals:
      - KC_HOSTNAME=https://keycloak.hashbang.sh
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
generators:
  - secret-generator.yaml
images:
  - name: quay.io/keycloak/keycloak
    newTag: 26.5.5@sha256:a7b0cb7a43a1235a61872883414d3f1d9a3ceac9df6e5907bd12202778a6265c
