apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/name: keycloak
resources:
  - ../cloudnative-pg/configurations
  - db.yaml
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - ingress.yaml
configMapGenerator:
  - name: keycloak-config
    literals:
      - KC_HOSTNAME=https://keycloak.hashbang.sh
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
generators:
  - secret-generator.yaml
images:
  - name: quay.io/keycloak/keycloak
    newTag: 26.7.0@sha256:0f198be292568439d700cdbfb893e69a6009bb43a94a06a945b1d3d506c76b13
