apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/name: keycloak
resources:
  - ../cloudnative-pg/configurations
  - db.yaml
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - ingress.yaml
configMapGenerator:
  - name: keycloak-config
    literals:
      - KC_HOSTNAME=https://keycloak.hashbang.sh
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
generators:
  - secret-generator.yaml
images:
  - name: quay.io/keycloak/keycloak
    newTag: 26.8.0@sha256:b0f60d489d51c5d113390bdf5461d4c06e6051be026c05549f2e1e10ec352bcc
