apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
resources:
  - github.com/james-callahan/cloudnative-pg-kustomize?ref=4f7c906c1baa22ff23afc66a013a5422b9e73e9b # branch=main
