apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb-api-deployment
  labels:
    app: userdb-api
spec:
  selector:
    matchLabels:
      app: userdb-api
  template:
    metadata:
      labels:
        app: userdb-api
    spec:
      containers:
      - name: postgrest
        image: postgrest/postgrest:v7.0.1
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: PGRST_DB_ANON_ROLE
          value: api-anon
        - name: PGRST_DB_SCHEMA
          value: v1
        - name: PGRST_DB_URI
          valueFrom:
            secretKeyRef:
              name: postgrest-secrets
              key: db-uri
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-api
  labels:
    app: userdb-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: userdb-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userdb-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: userdb.hashbang.sh
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nignx
  tls:
  - hosts:
    - userdb.hashbang.sh
    secretName: userdb-tls
  rules:
  - host: userdb.hashbang.sh
    http:
      paths:
      - path: /v1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: userdb-api
            port: 80
