apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matterbridge
resources:
- resources.yaml
configMapGenerator:
- name: matterbridge-config
  files:
  - files/matterbridge.toml
generators:
- secret-generator.yaml
images:
- name: 42wim/matterbridge
  newTag: 1.26.0@sha256:ba9ae3b54776d4e4a1317cd7929d62326f7d3dd75e37eb038e01e33e18e41164
