{
 "title": "UserDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Shell Hosts",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max without(instance,pod) (hosts_count)",
     "legendFormat": "Hosts"
    }
   ]
  },
  {
   "title": "Shell Users (Total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max without(instance, pod) (passwd_count)",
     "legendFormat": "Shell Users"
    }
   ]
  },
  {
   "title": "Users by Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Users on Host" }
   ],
   "targets": [
    {
     "expr": "max without(instance, pod) (passwd_host_count)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Shell Usage",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max without(instance, pod) (passwd_shell_count)",
     "legendFormat": "{{shell}}"
    }
   ]
  },
  {
   "title": "Group Statistics",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max without(instance, pod) (groups_count)",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}