{
 "title": "Shell Nodes",
 "description": "Shell Server Node Information",
 "time": { "from": "2020-06-29T14:53:55.451Z", "to": "2020-06-29T14:59:10.491Z" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_exporter_build_info{job=\"shell-server\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu:rate:sum{instance=\"$server\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\"}",
     "legendFormat": "Load Average (1m)"
    },
    {
     "expr": "node_load5{instance=\"$server\"}",
     "legendFormat": "Load Average (5m)"
    },
    {
     "expr": "node_load15{instance=\"$server\"}",
     "legendFormat": "Load Average (15m)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\"} - node_memory_MemFree_bytes{instance=\"$server\"} - node_memory_Buffers_bytes{instance=\"$server\"} - node_memory_Cached_bytes{instance=\"$server\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$server\"}",
     "legendFormat": "Buffered Memory"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$server\"}",
     "legendFormat": "Cached Memory"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$server\"}",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=\"$server\"} / node_memory_MemTotal_bytes{instance=\"$server\"} * 100)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$server\"}[$__interval])",
     "legendFormat": "{{instance}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$server\"}[$__interval])",
     "legendFormat": "{{instance}} written"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (max by(device) (node_filesystem_size_bytes{fstype!=\"tmpfs\", instance=\"$server\"} - node_filesystem_avail_bytes{fstype!=\"tmpfs\", instance=\"$server\"}))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum (max by(device) (node_filesystem_avail_bytes{fstype!=\"tmpfs\"}))",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$server\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$server\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}