apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repository.credentials: |
    - sshPrivateKeySecret:
        key: id_rsa
        name: ssh-key
      url: git@github.com:hashbang/gitops.git
