apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: argocd-ksops-secrets
files:
  - ./argocd-secret.enc.yaml

  # This secret contains
  # - an API Key for bitbot
  # - an API Key to `http://grafana.monitoring.svc/api`
  - ./argocd-notifications-secret.enc.yaml

  - ./deploy-key.enc.yaml
  - ./ssh-key.enc.yaml
