apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: team@hashbang.sh
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
    - selector:
        dnsZones:
          - "irc.hashbang.sh"
      dns01:
        route53:
          region: us-west-2
          accessKeyID: AIDAR7CEWFK3TPVRATH4J
          secretAccessKeySecretRef:
            name: dns-iam-key
            key: iam-key
