apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: controller
resources:
  - ingressclass.yaml
  - rbac.yaml
  - resources.yaml
  - webhook.yaml
images:
  - name: registry.k8s.io/ingress-nginx/controller
    newTag: v1.15.1@sha256:594ceea76b01c592858f803f9ff4d2cb40542cae2060410b2c95f75907d659e1
