apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-admission
spec:
  ports:
  - appProtocol: https
    name: https-webhook
    port: 443
    targetPort: webhook
  type: ClusterIP
