apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  project: default
  source:
    repoURL: git@github.com:hashbang/gitops.git
    path: monitoring/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
