apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site
spec:
  project: default
  source:
    repoURL: git@github.com:hashbang/gitops.git
    path: site/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: site
