apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userdb-api
spec:
  project: default
  source:
    repoURL: git@github.com:hashbang/gitops.git
    path: userdb-api/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: userdb-api
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
