apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
commonLabels:
  app.kubernetes.io/name: external-dns
resources:
- resources.yaml
- networkpolicy.yaml
- service-monitor.yaml
patches:
- path: aws_credentials.yaml
generators:
- secret-generator.yaml
images:
- name: registry.k8s.io/external-dns/external-dns
  newTag: v0.22.0@sha256:5fdcaf7deb5c158f93a1fc6fe169cdff4cfb9ae0172bee1a90ab0ef74fb9c9cf
