# https://github.com/kubernetes-sigs/external-dns/blob/v0.13.1/docs/tutorials/aws.md#manifest-for-clusters-with-rbac-enabled
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: ['']
  resources: ['endpoints', 'pods', 'services']
  verbs: ['get', 'watch', 'list']
- apiGroups: ['extensions']
  resources: ['ingresses']
  verbs: ['get', 'watch', 'list']
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "list"]
# Rules for DNS Endpoints CRD
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints"]
  verbs: ["get","watch","list"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints/status"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns
        args:
        - --source=service
        - --source=ingress
        - --registry=txt
        - --provider=aws
        - --txt-owner-id=digitalocean-hashbang
        - --txt-prefix=_owner.
        - --source=crd
        - --domain-filter=hashbang.sh
        - --managed-record-types=A
        - --managed-record-types=CNAME
        - --managed-record-types=TXT
        ports:
        - containerPort: 7979
          name: metrics
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
