apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-dns-server-metrics
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    prometheusInstance: default
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
