apiVersion: v1
kind: Service
metadata:
  name: external-dns
  labels:
    app: external-dns
spec:
  ports:
  - name: metrics
    port: 7979
    targetPort: 7979
  selector:
    app: external-dns
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-dns-server-metrics
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    prometheusInstance: default
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: external-dns
