apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mtls
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mtls.hashbang.sh
    secretName: mtls-tls
