apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb
  namespace: jitsi
spec:
  type: LoadBalancer
  ports:
  - port: 10000
    protocol: UDP
    name: rtp-udp
  selector:
    app.kubernetes.io/name: jvb
