---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jitsi
  namespace: jitsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jicofo
    app.kubernetes.io/part-of: jitsi
  name: jicofo
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jicofo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jicofo
    spec:
      containers:
        - name: jicofo
          image: jitsi/jicofo:stable-8922-1
          imagePullPolicy: IfNotPresent
          env:
          - name: PUBLIC_URL
            value: https://meet.hashbang.sh
          - name: XMPP_SERVER
            value: prosody.jitsi.svc.cluster.local
          - name: XMPP_DOMAIN
            value: meet.jitsi
          - name: XMPP_AUTH_DOMAIN
            value: auth.meet.jitsi
          - name: XMPP_MUC_DOMAIN
            value: muc.meet.jitsi
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: internal-muc.meet.jitsi
          - name: JICOFO_COMPONENT_SECRET
            valueFrom:
              secretKeyRef:
                name: jitsi-config
                key: JICOFO_COMPONENT_SECRET
          - name: JICOFO_AUTH_USER
            value: focus
          - name: JICOFO_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jitsi-config
                key: JICOFO_AUTH_PASSWORD
          - name: TZ
            value: America/Los_Angeles
          - name: JVB_BREWERY_MUC
            value: jvbbrewery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prosody
    app.kubernetes.io/part-of: jitsi
  name: prosody
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prosody
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prosody
    spec:
      containers:
        - name: prosody
          image: jitsi/prosody:stable-8922-1
          imagePullPolicy: IfNotPresent
          env:
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: PUBLIC_URL
              value: https://meet.hashbang.sh
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: America/Los_Angeles
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: jitsi
  name: web
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
        - name: web
          image: jitsi/web:stable-8922-1
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBLIC_URL
              value: https://meet.hashbang.sh
            - name: XMPP_SERVER
              value: prosody.jitsi.svc.cluster.local
            - name: JICOFO_AUTH_USER
              value: focus
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://prosody.jitsi.svc.cluster.local:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: America/Los_Angeles
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jvb
    app.kubernetes.io/part-of: jitsi
  name: jvb
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jvb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jvb
    spec:
      containers:
        - name: jvb
          image: jitsi/jvb:stable-8922-1
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBLIC_URL
              value: https://meet.hashbang.sh
            - name: XMPP_SERVER
              value: prosody.jitsi.svc.cluster.local
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JVB_STUN_SERVERS
              value: meet-jit-si-turnrelay.jitsi.net:443
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "true"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "10000"
            - name: JVB_WS_SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: America/Los_Angeles
      serviceAccountName: jitsi
---
